apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencart-deployment
  labels:
    app: opencart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencart
  template:
    metadata:
      labels:
        app: opencart
    spec:
      containers:
      - name: opencart
        image: severchyk/opencart:2.3.0.2-centos-7
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: opencart
spec:
  selector:
    app: opencart
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: opencart-deployment
spec:
  type: ExternalName
  externalName: dev-opencart-db.cq4nyvfqewas.us-east-2.rds.amazonaws.com